baseURL = 'https://hub-media.pages.dev/'
languageCode = 'fr-FR'
title = 'Media Native'
theme = 'blowfish'

[params]
  colorScheme = "system"
  defaultTheme = "system"
  showReadingTime = true
  showAuthor = true
  
  [params.homepage]
    layout = "profile"
    showRecent = true
    cardView = true

[params.sidebar]
  enable = true
  homepage = true
  open = true

[menu]
  [[menu.main]]
    name = "Accueil"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "Vidéos"
    pageRef = "/videos/"
    weight = 20
  [[menu.main]]
    name = "Recherche"
    pageRef = "/search/"
    weight = 30

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'

[build.buildStats]
  disableClasses = false
  disableIDs = false
  disableTags = false
  enable = false

[[build.cacheBusters]]
  source = '(postcss|tailwind)\.config\.(js|mjs|cjs)'
  target = '(css|styles|scss|sass)'

[build.cleanDestinationDir]
  enable = false
  keepDirs = ['{**/,}.*']
  keepFiles = ['{**/,}.{git,gitignore,gitattributes}']

