baseURL = 'https://hub-media.pages.dev/'
languageCode = 'fr-FR'
title = 'Media Native'
theme = 'blowfish'

[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'

[build.buildStats]
  disableClasses = false
  disableIDs = false
  disableTags = false
  enable = false

[[build.cacheBusters]]
  source = '(postcss|tailwind)\.config\.(js|mjs|cjs)'
  target = '(css|styles|scss|sass)'

[build.cleanDestinationDir]
  enable = false
  keepDirs = ['{**/,}.*']
  keepFiles = ['{**/,}.{git,gitignore,gitattributes}']
