baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Media Native | Sabar'
theme = 'blowfish'
paginate = 6

[markup.goldmark.renderer]
  unsafe = true

[params]
  site_author = "Sabar"
  description = "Média interactif : analyses, vidéos"
  background_color_class = "bg-black"
  recent_posts_number = 4

[[menu.main]]
  name = "Accueil"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Vidéos"
  pageRef = "/videos/"
  weight = 2
